# This is a basic workflow to help you get started with Actions

name: Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Add depot_tools to PATH
        run: |
          DEPOT_TOOLS_PATH=$(realpath ./depot_tools)
          echo $DEPOT_TOOLS_PATH
          echo "$DEPOT_TOOLS_PATH" >> $GITHUB_PATH
          
      - name: Update depot_tools
        run: gclient
        
      - name: Fetch v8
        run: fetch v8
          
      - name: Build v8 Deps
        run: |
          cd v8
          gclient sync
          ./build/install-build-deps.sh
          
      - name: Build Release & Debug v8
        run: |
          cd v8
          ./tools/dev/gm.py x64.release & ./tools/dev/gm.py x64.debug

      - name: Zip Builds
        run: zip -r v8-release.zip ./v8/out/x64.release & zip -r v8-debug.zip ./v8/out/x64.debug
        
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            v8-release.zip
            v8-debug.zip
